"""Required executable reference implementations for public Mojo functions."""

from mojo_opset.utils._exports import extend_bindings as _extend_bindings

OPS = {
    "rms_norm_quant": "fused_quantization",
    "layer_norm_quant": "fused_quantization",
    "residual_add_rms_norm_quant": "fused_quantization",
    "residual_add_layer_norm_quant": "fused_quantization",
    "moe_dynamic_quant": "fused_quantization",
    "dequant_swiglu_quant": "fused_quantization",
    "rotate_activation": "rotate_activation",
    "flex_attention": "flex_attention",
    "flex_attention_v2": "flex_attention_v2",
    "rotary_embedding": "rotary_embedding",
    "vision_rotary_embedding2d": "rotary_embedding",
    "mrope": "mrope",
    "sdpa_infer": "sdpa",
    "diffusion_attention": "sdpa",
    "n_gram_prefill": "over_encoding",
    "n_gram_decode": "over_encoding",
    "embedding_nf4_dequant": "over_encoding",
    "over_encoding_decode": "over_encoding",
    "lightning_indexer": "indexer",
    "store_lowrank": "store_lowrank",
    "apply_rope_infer": "position_embedding",
    "apply_vision_rope2d_infer": "position_embedding",
    "paged_decode_gqa_infer": "paged_attention",
    "paged_prefill_gqa_infer": "paged_attention",
    "paged_prefill_swa_infer": "paged_attention",
    "paged_decode_swa_infer": "paged_attention",
    "prefill_gqa_infer": "paged_attention",
    "store_paged_kv_cache": "kv_cache",
    "quant_batch_gemm_reduce_sum": "gemm",
    "top_k_sampling": "sampling",
    "top_p_sampling": "sampling",
    "top_p_filter": "sampling",
    "reject_sampling": "sampling",
    "join_prob_reject_sampling": "sampling",
    "apply_penalties_temperature": "sampling",
    "group_gemm": "gemm",
    "quant_gemm": "gemm",
    "static_quant": "quantization",
    "dequant": "quantization",
    "dynamic_quant": "quantization",
    "varlen_fa_infer": "varlen_fa",
    "linear_cross_entropy": "linear_cross_entropy",
    "linear_cross_entropy_v2": "linear_cross_entropy_v2",
    "linear_cross_entropy_v2_and_zloss": "linear_cross_entropy_v2",
    "causal_conv1d_update_state_infer": "convolution",
    "layer_norm_infer": "normalization",
    "rms_norm_infer": "normalization",
    "group_rms_norm_infer": "normalization",
    "residual_add_layer_norm_infer": "normalization",
    "residual_add_rms_norm_infer": "normalization",
    "causal_conv1d": "convolution",
    "flash_attention": "attention",
    "flash_attention_infer": "attention",
    "silu": "silu",
    "gelu": "gelu",
    "swiglu": "swiglu",
    "rms_norm": "rms_norm",
    "swa": "attention",
    "swa_infer": "attention",
    "native_swa_infer": "attention",
    "apply_rope": "apply_rope",
}


_extend_bindings(__name__, OPS)
del _extend_bindings
