#pragma once

#ifndef CUSTOM_FA_ABLATION_LEVEL
#define CUSTOM_FA_ABLATION_LEVEL 8
#endif

#if CUSTOM_FA_ABLATION_LEVEL < 0 || CUSTOM_FA_ABLATION_LEVEL > 8
#error "CUSTOM_FA_ABLATION_LEVEL must be in [0, 8]"
#endif

#ifndef CUSTOM_FA_FULL_SKIP_MASK
#if CUSTOM_FA_ABLATION_LEVEL >= 1
#define CUSTOM_FA_FULL_SKIP_MASK 1
#else
#define CUSTOM_FA_FULL_SKIP_MASK 0
#endif
#endif

#ifndef CUSTOM_FA_TILE_KV
#if CUSTOM_FA_ABLATION_LEVEL >= 2
#define CUSTOM_FA_TILE_KV 1024
#else
#define CUSTOM_FA_TILE_KV 512
#endif
#endif

#ifndef CUSTOM_FA_MMAD_L0_STAGE_NUM
#if CUSTOM_FA_ABLATION_LEVEL >= 3
#define CUSTOM_FA_MMAD_L0_STAGE_NUM 2
#else
#define CUSTOM_FA_MMAD_L0_STAGE_NUM 1
#endif
#endif

#ifndef CUSTOM_FA_FULL_BLOCK_KV
#if CUSTOM_FA_ABLATION_LEVEL >= 4
#define CUSTOM_FA_FULL_BLOCK_KV 256
#else
#define CUSTOM_FA_FULL_BLOCK_KV 128
#endif
#endif

#ifndef CUSTOM_FA_ENABLE_LONG_FULL_STAGE3
#if CUSTOM_FA_ABLATION_LEVEL >= 5
#define CUSTOM_FA_ENABLE_LONG_FULL_STAGE3 1
#else
#define CUSTOM_FA_ENABLE_LONG_FULL_STAGE3 0
#endif
#endif

#ifndef CUSTOM_FA_FULL_STAGE3_MIN_SEQ_LEN
#define CUSTOM_FA_FULL_STAGE3_MIN_SEQ_LEN 4096
#endif

#ifndef CUSTOM_FA_GQA_FULL_STAGE3_MIN_SEQ_LEN
#define CUSTOM_FA_GQA_FULL_STAGE3_MIN_SEQ_LEN CUSTOM_FA_FULL_STAGE3_MIN_SEQ_LEN
#endif

#ifndef CUSTOM_FA_L0_REDUCE_SIZE_PV
#if CUSTOM_FA_ABLATION_LEVEL >= 6
#define CUSTOM_FA_L0_REDUCE_SIZE_PV 128
#else
#define CUSTOM_FA_L0_REDUCE_SIZE_PV 64
#endif
#endif

#ifndef CUSTOM_FA_ENABLE_SOFTMAX_FLASH_V2
#if CUSTOM_FA_ABLATION_LEVEL >= 7
#define CUSTOM_FA_ENABLE_SOFTMAX_FLASH_V2 1
#else
#define CUSTOM_FA_ENABLE_SOFTMAX_FLASH_V2 0
#endif
#endif

#ifndef CUSTOM_FA_L2_BYPASS_QUERY
#if CUSTOM_FA_ABLATION_LEVEL >= 8
#define CUSTOM_FA_L2_BYPASS_QUERY 1
#else
#define CUSTOM_FA_L2_BYPASS_QUERY 0
#endif
#endif

#ifndef CUSTOM_FA_L2_BYPASS_OUTPUT
#if CUSTOM_FA_ABLATION_LEVEL >= 8
#define CUSTOM_FA_L2_BYPASS_OUTPUT 1
#else
#define CUSTOM_FA_L2_BYPASS_OUTPUT 0
#endif
#endif

#ifndef CUSTOM_FA_ENABLE_SOFTMAX_FUSED_VEC_OPS
#define CUSTOM_FA_ENABLE_SOFTMAX_FUSED_VEC_OPS 0
#endif

#ifndef CUSTOM_FA_ENABLE_AGGREGATE_FUSED_VEC_OPS
#define CUSTOM_FA_ENABLE_AGGREGATE_FUSED_VEC_OPS 0
#endif

#ifndef CUSTOM_FA_SOFTMAX_FLASH_V2_BASIC_BLOCK
#define CUSTOM_FA_SOFTMAX_FLASH_V2_BASIC_BLOCK 1
#endif

#ifndef CUSTOM_FA_HOIST_SOFTMAX_SCALE_DUP
#define CUSTOM_FA_HOIST_SOFTMAX_SCALE_DUP 1
#endif

#ifndef CUSTOM_FA_SOFTMAX_USE_COUNTER_MASK
#define CUSTOM_FA_SOFTMAX_USE_COUNTER_MASK 0
#endif

#ifndef CUSTOM_FA_AGGREGATE_USE_COUNTER_MASK
#define CUSTOM_FA_AGGREGATE_USE_COUNTER_MASK 0
#endif

#if CUSTOM_FA_TILE_KV != 128 && CUSTOM_FA_TILE_KV != 256 && CUSTOM_FA_TILE_KV != 512 && CUSTOM_FA_TILE_KV != 1024 && CUSTOM_FA_TILE_KV != 2048
#error "CUSTOM_FA_TILE_KV must be 512 or 1024"
#endif

#if CUSTOM_FA_FULL_BLOCK_KV != 128 && CUSTOM_FA_FULL_BLOCK_KV != 256
#error "CUSTOM_FA_FULL_BLOCK_KV must be 128 or 256"
#endif

#if CUSTOM_FA_MMAD_L0_STAGE_NUM != 1 && CUSTOM_FA_MMAD_L0_STAGE_NUM != 2
#error "CUSTOM_FA_MMAD_L0_STAGE_NUM must be 1 or 2"
#endif

#if CUSTOM_FA_L0_REDUCE_SIZE_PV != 64 && CUSTOM_FA_L0_REDUCE_SIZE_PV != 128
#error "CUSTOM_FA_L0_REDUCE_SIZE_PV must be 64 or 128"
#endif
